export const GET_ALL_COWS_REQUEST = "GET_ALL_COWS_REQUEST"
export const GET_ALL_COWS_FAILURE = "GET_ALL_COWS_FAILURE"
export const GET_ALL_COWS_SUCCESS = "GET_ALL_COWS_SUCCESS"



export const GET_ALL_DISEASE_REQUEST = "GET_ALL_DISEASE_REQUEST"
export const GET_ALL_DISEASE_FAILURE = "GET_ALL_DISEASE_FAILURE"
export const GET_ALL_DISEASE_SUCCESS = "GET_ALL_DISEASE_SUCCESS"
